default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: pg
  host: ec2-54-204-41-178.compute-1.amazonaws.com
  database: d7e66j2fhtrdp4   
  user: 'eovtvaoveswspu'
  password: 'xVfIqZ1Si6p6yy67X7aI891PWV'
