development: 
  adapter: mysql
  database: test
  password: 123456
  user: root
production: 
  adapter: postgresql
  database: deif59mhimcl7p
  host: ec2-23-21-101-129.compute-1.amazonaws.com
  password: UWFkOrHBPdLE68uUKAU4qXn6A8
  user: uurcnkqfutvrwq
test: 
  adapter: mysql
  database: test
  password: 123456
  user: root
