development: 
  adapter: mysql
  database: test
  password: 123456
  user: root
production: 
  adapter: postgresql
  database: d7e66j2fhtrdp4
  host: ec2-54-204-41-178.compute-1.amazonaws.com
  password: xVfIqZ1Si6p6yy67X7aI891PWV
  user: eovtvaoveswspu
test: 
  adapter: mysql
  database: test
  password: 123456
  user: root
